# Generated by Django 6.0.4 on 2026-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('intent_confidence', models.FloatField(default=0.0)),
                ('urgency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('routing_department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
    ]
